In [1]:
import numpy as np  # Importa a biblioteca NumPy para manipulação de arrays

# Definindo a função Scaled Dot-Product Attention
def scaled_dot_product_attention(Q, K, V):
    """
    Calcula a atenção usando Q, K e V.
    """
    d_k = Q.shape[-1]  # Obtém a dimensão dos vetores de chave (K)

    # Calcula o produto escalar entre Q e K transposto
    scores = np.dot(Q, K.T) / np.sqrt(d_k)

    # Aplica softmax para obter os pesos de atenção
    attention_weights = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)

    # Multiplica os pesos pela matriz V para obter o vetor de saída
    output = np.dot(attention_weights, V)

    return output, attention_weights  # Retorna a saída e os pesos de atenção

# Simulando vetores Q, K e V para um exemplo simples
np.random.seed(0)  # Define a seed para reprodutibilidade
Q = np.random.rand(3, 4)  # 3 tokens, dimensão 4
K = np.random.rand(3, 4)  # 3 tokens, dimensão 4
V = np.random.rand(3, 4)  # 3 tokens, dimensão 4

# Calcula a atenção
attention_output, attention_weights = scaled_dot_product_attention(Q, K, V)

print("Pesos de Atenção (softmax):\n", attention_weights)  # Exibe os pesos de atenção
print("\nResultado da Atenção:\n", attention_output)  # Exibe a saída da atenção


Pesos de Atenção (softmax):
 [[0.26820899 0.341926   0.38986501]
 [0.25100881 0.35895866 0.39003253]
 [0.25670316 0.31516267 0.42813417]]

Resultado da Atenção:
 [[0.38799283 0.53502878 0.13623257 0.75889379]
 [0.39492337 0.53118004 0.1382761  0.75593604]
 [0.39012207 0.53832171 0.12822185 0.75093991]]
